apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmCharts:
  - name: eks-chart
    includeCRDs: true
    namespace: aws-controllers
    valuesInline:
      aws.region: ap-southeast-2
    version: v0.1.1


resources:
  - namespace.yaml
