apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmCharts:
  - name: eks-chart
    includeCRDs: true
    namespace: aws-controllers
    valuesInline: {}
    version: v0.1.1


